[package]
name = "axum_auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.7"
serde_json = "1.0.128"
tower-livereload = "0.9.4"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
# validator = { version = "0.16.1", features = ["derive"] }
axum-valid = { version = "0.20.0", default-features = false, features = ["garde", "basic"] }
tower-http = { version = "0.6.1", features = ["trace"] }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
garde = { version = "0.20.0", features = ["full"] }
diesel = { version = "2.2.0", features = ["postgres"] }
dotenv = "0.15.0"
chrono = "0.4.38"

