version: "3.9"
name: ${PROJECT}

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT}_nginx
    ports:
      - "80:80"
      - "443:443" # Add HTTPS port
    networks:
      - external_network
    restart: always

networks:
  external_network:
    name: ${PROJECT}_network
    external: true
