version: "3.9"
name: ${PROJECT}

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT}_nginx
    env_file:
      - .env.prod
    ports:
      - "80:80"
      - "443:443" # For HTTPS
    volumes:
      - ./ssl:/etc/nginx/ssl:ro # For SSL certificates
    networks:
      - external_network
    restart: always

networks:
  external_network:
    name: ${PROJECT}_network
    external: true
