version: "3.9"
name: ${PROJECT}

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${PROJECT}_nginx
    env_file:
      - .env.dev
    ports:
      - "80:80"
    networks:
      - external_network
    restart: always

networks:
  external_network:
    name: ${PROJECT}_network
    external: true
